AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

PAYMENT_PROVIDER_SECRET = "live_token_51HxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxFAKE"

PRIVATE_KEY_PEM = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
NOT_A_REAL_KEY_BUT_LOOKS_LIKE_ONE_FOR_TESTING_SCANNERS
-----END RSA PRIVATE KEY-----"""
